### ISSUE TITLE
The image folder specified does not exist, use the colab file explorer to copy the path

### ISSUE THREAD

**Issue by search620** [tuwonga/fast_Dreambooth_4_kaggle#1]
I get this no matter what my input is

**Comment by tuwonga** [comment]
the image folder is the path of your data set in kaggle.
I wrote it in the readme file.
Example: I've created a data set called "photograph" with my profile photos, before running the code.
In the notebook you can see on the right panel "ADD DATA" and you can add your data set created by using the "+" symbol so the system can upload your data set (image folder) as ready to use.
For me the path of the image folder is "/kaggle/input/d/my_kaggle_account/photograph\".
"my_kaggle_account" for me is my name and surname, maybe the system makes as default your name and surname during registration on kaggle.
By the way, to check where data set really is you can open the console and send:
cd /kaggle/input
then:
ls (to show directories and folder)
and so on... until you'll find your data set folder (in my case "photograph")

let me know

**Comment by search620** [comment]
My dear friend if you can help me to achieve it by TeamViewer, it can be a bomb good.
Buy I have a flight tomorrow in the evening so if you can and want this is the right moment and if you can't so., I don't know what to do

**Comment by tuwonga** [comment]
I'm sorry, I came back home right now and I'm going to sleep. I will help you next days if you want. send me pvt msg as soon as you can (on reddit).
Thank you.

**Comment by search620** [comment]
I wish I will cath you in time. I am going from tomorrow to be on my flight I back just in 1 week from now. can you please send me where I can get you on Reddit?

**Comment by search620** [comment]
OK so I am back and still didn't succeed to make it work. if you can help me 1 by 1 it can be great!

**Comment by tuwonga** [comment]
> OK so I am back and still didn't succeed to make it work. if you can help me 1 by 1 it can be great!

please use reddit do not send msg here. thank you
