### ISSUE TITLE
fix the errors

### ISSUE THREAD

**Issue by Rasad0** [tuwonga/fast_Dreambooth_4_kaggle#10]
bro every code is getting errors literally. I hope you will fix it

**Comment by tuwonga** [comment]
I'm sorry, I fixed today but only for 1.5.
It works for me.
Let me know.
Thank you

**Comment by tuwonga** [comment]
Hello,
I've ported the recent version of the fast_dreambooth suitable for stable 1.5 and 2.1 version.
I've tried and trained a V2-512 and it works.
Hope will be ok also for you.
Don't forget to edit "your_instance_folder" and "your_instance_name".
The repo  1.5-v2 was edited by me with a loaded stable diffusion v2.1-512 base model from huggingface but you can use whatever you like with the format "profile/model" (from huggingface). 
Please read the markdown.
Thank you.
