### ISSUE TITLE
The image folder specified does not exist, use the colab file explorer to copy the path :

### ISSUE THREAD

**Issue by 7wpanc24** [tuwonga/fast_Dreambooth_4_kaggle#4]
No matter what I do I still get this message when it comes time to load the training images. I tried everything I coould think of or google.

**Comment by tuwonga** [comment]
You have to upload your images.
To do that you have to create a dataset in kaggle and then copy the path.
Read the readme file, you have to edit the ipynb with your personal instance name and instance folder every time is needed.
In the cell :
`!cp -r /kaggle/input/your_images_data_folder /kaggle/working/my`
you need to replace "your_images_data_folder" with the name of your datased created.
This will fix your error.

**Comment by 7wpanc24** [comment]
Thank you for your response. I followed the readme file and did that, but received that error. I tried loading the dataset into the notebook - same issue, using the url - same issue, attempted to replace the code to download from a google drive folder - a new issue. not sure where to go from there. any help would be appreciated.

**Comment by tuwonga** [comment]
you have to create e new data set in kaggle.
do you have an account in kaggle ? make a dataset with your images (images data for training).
Name your datafolder, this will be the your_images_data_folder name to replaced in this code cell >` !cp -r /kaggle/input/your_images_data_folder /kaggle/working/my`

**Comment by 7wpanc24** [comment]
I do have a kaggle account and did that.

**Comment by 7wpanc24** [comment]
i should note that this is in the text encoder version

**Comment by 7wpanc24** [comment]
it appears that the code there is significantly different in the text encoder version than in the regular version.

**Comment by 7wpanc24** [comment]
just tried the non-text encoder version and am encountering the same issue

**Comment by 7wpanc24** [comment]
Have tried a number of ways to troubleshoot, thought i might have cracked it, but now I'm getting "/kaggle/working/my' is not a directory". Is that line correct? I'm not finding that directory anywhere else in the code.

**Comment by tuwonga** [comment]
> Have tried a number of ways to troubleshoot, thought i might have cracked it, but now I'm getting "/kaggle/working/my' is not a directory". Is that line correct? I'm not finding that directory anywhere else in the code.

the command create the /kaggle/working/my and copythe content of /kaggle/input/your_images_data_folder inside it.
If you have problem you can add this cell before :
`mkdir /kaggle/working/my`

**Comment by tuwonga** [comment]
> Have tried a number of ways to troubleshoot, thought i might have cracked it, but now I'm getting "/kaggle/working/my' is not a directory". Is that line correct? I'm not finding that directory anywhere else in the code.

please when you need to report an issue copy the code and line with error otherwise it's not easy to understand what kind of issue you have.
thank you.

**Comment by search620** [comment]
Same problem here.... can't get it work. 

![image](https://user-images.githubusercontent.com/56544202/203012070-6584efff-73fb-4654-b2f4-c0149f9e6a09.png)

**Comment by tuwonga** [comment]
> Same problem here.... can't get it work.
> 
> ![image](https://user-images.githubusercontent.com/56544202/203012070-6584efff-73fb-4654-b2f4-c0149f9e6a09.png)

Well, the files must be free in the folder.
![Senza titolo-1](https://user-images.githubusercontent.com/110191792/203121242-16c1db35-ee80-4ead-8b60-c36bc5920309.jpg)
In my case the data folder path is /kaggle/input/rotoscopee

**Comment by search620** [comment]
> > Same problem here.... can't get it work.
> > ![image](https://user-images.githubusercontent.com/56544202/203012070-6584efff-73fb-4654-b2f4-c0149f9e6a09.png)
> 
> Well, the files must be free in the folder. ![Senza titolo-1](https://user-images.githubusercontent.com/110191792/203121242-16c1db35-ee80-4ead-8b60-c36bc5920309.jpg) In my case the data folder path is /kaggle/input/rotoscopee

What do you mean the files need to be free in the folder?
and what about this button that copies the path of the files? 

![image](https://user-images.githubusercontent.com/56544202/203123430-e3660e2c-95cf-42a7-8f91-54a82d4cad0d.png)

**Comment by tuwonga** [comment]
you're right but you have a folder "train" under the folder "nataleetest".
In my case I have all the image under the folder "rotoscopee".
By the way in the latest repo I've added the line `mkdir /kaggle/working/my` before the line `/kaggle/input/your_images_data_folder /kaggle/working/my` so if everything is correct the images will be picked by code from the folder /kaggle/working/my.
Of course you have to edit correctly the input image data path.
A I told you, I created the dataset with the same name of imeages.
I will post you a pic.

**Comment by search620** [comment]
Ok, thanks for your reply I try to fix it somehow...

I try lots of combinations for the path as shown in the screenshot below but nothing work so far

![image](https://user-images.githubusercontent.com/56544202/203126352-96f3f2fd-14b6-4cc5-968e-8b44905b8391.png)

**Comment by tuwonga** [comment]
> Ok, thanks for your reply I try to fix it somehow...
> 
> I try lots of combinations for the path as shown in the screenshot below but nothing work so far
> 
> ![image](https://user-images.githubusercontent.com/56544202/203126352-96f3f2fd-14b6-4cc5-968e-8b44905b8391.png)

delete the dataset and make a new one.

**Comment by search620** [comment]
Ok, I did and now the next step is in process let's hope for the best :) by the way, can I keep the correct position (If all goes well) Without having to download the model again every time?

![image](https://user-images.githubusercontent.com/56544202/203128097-d4af1c7c-7b05-4ac8-8721-d01358bccd01.png)

**Comment by tuwonga** [comment]
![Senza titolo](https://user-images.githubusercontent.com/110191792/203128930-6fd33103-df3f-4e55-8e8d-c720878659cf.jpg)

**Comment by search620** [comment]
well, I can't get it running. I share with you an open link and if you can please take a look and see if I do something wrong here

https://www.kaggle.com/code/lirangaston/notebookac831967bf

**Comment by tuwonga** [comment]
> Ok, I did and now the next step is in process let's hope for the best :) by the way, can I keep the correct position (If all goes well) Without having to download the model again every time?
> 
> ![image](https://user-images.githubusercontent.com/56544202/203128097-d4af1c7c-7b05-4ac8-8721-d01358bccd01.png)

you need to stop the cell and run again to upload the images to train

**Comment by tuwonga** [comment]
please do not run all the cells but one cell at time

**Comment by tuwonga** [comment]
> well, I can't get it running. I share with you an open link and if you can please take a look and see if I do something wrong here
> 
> https://www.kaggle.com/code/lirangaston/notebookac831967bf

404 error, I can't see the page.
Please download the code now, I've fixed. deleted the mkdir `/kaggle/working/my` cell.
I'm training now with the code and everythiing is fine.
