### ISSUE TITLE
Error on training cell

### ISSUE THREAD

**Issue by Plecko** [tuwonga/fast_Dreambooth_4_kaggle#7]
Hi there, 

Was using your fantastic dreambooth port on here for a few weeks perfectly, but it seems like i'm having issues since SD2.0 and various other updates.

I'm trying to train on 1.5 and every time I get an error when it gets to the training cell. 

I feel like i'm inputting all my session name, instance name etc in all the right places, as I was before, but I must be doing something wrong. 

Any advice would be appreciated. 

<img width="1021" alt="Screenshot 2022-12-01 at 00 26 48" src="https://user-images.githubusercontent.com/112208414/204936983-b81d513a-e3a3-4a42-b82d-b7532353042a.png">
 
Thanks!

**Comment by tuwonga** [comment]
fixed
