### ISSUE TITLE
Trying to train on v2 — "No model found, use the "Model Download" cell to download a model."

### ISSUE THREAD

**Issue by Plecko** [tuwonga/fast_Dreambooth_4_kaggle#8]
I've had great success with training on 1.5. Just tried to train on the v2 model (512) and I keep getting the following error on the training cell.

"No model found, use the "Model Download" cell to download a model."

I've tried using a link from the model on my google drive, i've tried directly linking to the huggingface CKPT (https://huggingface.co/stabilityai/stable-diffusion-2-base/resolve/main/512-base-ema.ckpt)

But i'm obviously doing something wrong.

Any help would be appreciated, thank you.

<img width="941" alt="Screenshot 2022-12-04 at 19 59 23" src="https://user-images.githubusercontent.com/112208414/205512722-c81048fe-2dfc-4f40-a475-5c038477cdf8.png">

**Comment by tuwonga** [comment]
do you have to edit your huggingface token.

`Huggingface_Token = "your token" #@param {type:"string"}`

**Comment by Plecko** [comment]
I'll try it — I assumed that it needed to be left blank:

_Leave EMPTY if you're using the v2 model_

**Comment by tuwonga** [comment]
dear,
I've tried right now with my huggingface write token and I did.
![image](https://user-images.githubusercontent.com/110191792/205516812-0ac6a1ed-abc4-4d76-b91c-1ed9e729a115.png)

**Comment by Plecko** [comment]
Hmm that's what mine looks like, and i am still getting model not found error at the training cell...

I tried inputting my huggingface token, but that didn't work.

For V2-512, what is the exact huggingface url to put in this section? 

Path_to_HuggingFace= "" #@param {type:"string"}

**Comment by Plecko** [comment]
I will try again with just the hugging face token and no other links.

**Comment by tuwonga** [comment]
no Path to but the line above
I wrote you in previous message

**Comment by Plecko** [comment]
thank you, that did solve it in the end. I opened a fresh notebook and only put in the huggingface token and it worked. I was confused by the line that says "Leave EMPTY if you're using the v2 model"

<img width="954" alt="Screenshot 2022-12-05 at 00 52 50" src="https://user-images.githubusercontent.com/112208414/205528038-17874b0e-8856-4a17-a31c-a062c4723cc8.png">

However, after finishing training for 3 hours on v2-512, it ran out drive space to save my model sadly. I wasn't able to write the .cpkt to the /working folder and so I wasn't able to download it.

Do you have any advice for this?

**Comment by tuwonga** [comment]
why don't you have space into drive?
maybe you didn't delete the files from previous sessions.
During notebook, on the right kaggle panel there is a setting tab. You have to check "persistence" and edit with no persistence so you don't keep any files or variables from previous sessions.

**Comment by tuwonga** [comment]
I also suggest you to delete the old dataset to get more free space.

**Comment by Plecko** [comment]
I'm not sure to be honest, but I don't know how to use Kaggle properly!

I will delete old datasets, but they are probably only around 200mb in size total.

My persistence is set to 'no persistence' so i'm not sure what the issue is. 

I just tried another v2-512 run, with less steps just to test it and it failed again, not enough space to write to drive.

Not sure what to do or why how its going from 0 to 19.5gb in one run. Just seems like v2-512 is taking up too much space somehow.

<img width="1680" alt="Screenshot 2022-12-05 at 13 33 50" src="https://user-images.githubusercontent.com/112208414/205651021-e19c4619-952b-4c4d-9897-b2fd2dcd95b6.png">

**Comment by Plecko** [comment]
This is how my session starts:

<img width="440" alt="Screenshot 2022-12-05 at 13 45 48" src="https://user-images.githubusercontent.com/112208414/205652286-e840df4a-9eef-4922-a9a0-1bb4e4bdb073.png">

**Comment by tuwonga** [comment]
maybe you're right, I will try

**Comment by Plecko** [comment]
I may have a workaround. I am waiting for the training to finish in one hour.

I added this:

```
import shutil
shutil.rmtree("/kaggle/working/content/stable-diffusion-v2-512")
```

After the training, before it is turned into a .ckpt file.

It might not work, but in theory it will delete the stable-diffusion-v2-512 directory after training is complete, to free up space to save the model. 

I will report back soon.

<img width="983" alt="Screenshot 2022-12-05 at 16 48 29" src="https://user-images.githubusercontent.com/112208414/205694813-12384261-3d1e-438e-a724-a11c35743ce2.png">

**Comment by tuwonga** [comment]
might be a great fix

**Comment by Plecko** [comment]
Yup, that worked!

Haven't tested the model yet, but it saved fine and i'm downloading it now. Final space was 14.5GB / 19.5GB.

I'll mark this as closed.

**Comment by tuwonga** [comment]
> Yup, that worked!
> 
> Haven't tested the model yet, but it saved fine and i'm downloading it now. Final space was 14.5GB / 19.5GB.
> 
> I'll mark this as closed.

if you want to pull request for commits I will be glad to merge. Thank you.
