### ISSUE TITLE
Can't train v1.5 model

### ISSUE THREAD

**Issue by GoldenDog1218** [tuwonga/fast_Dreambooth_4_kaggle#9]
at first it with stuck at download model with an error(run with Path_to_HuggingFace=)
![QQ截图20230113142345](https://user-images.githubusercontent.com/78063969/212251935-8085ec9c-6d11-4a76-bc81-2a20fbee47c4.png)
if i edit code to skip this error, it with have someting wrong when i train
![QQ截图20230113143938](https://user-images.githubusercontent.com/78063969/212254258-2a348e5c-d66d-4074-870e-a05bab335068.png)
and this is my setting on downlaod model
![QQ截图20230113144043](https://user-images.githubusercontent.com/78063969/212254473-80b67db3-87fd-4c7d-a2a7-bf973618484e.png)

**Comment by tuwonga** [comment]
1.5 model requires your huggingface access token

**Comment by GoldenDog1218** [comment]
> 

I entered token, but it was removed during screenshot,
After selecting v1.5 model, I will encounter a variable "V2_model" that has not been declared. I can skip this judgment by using parameters such as 1>2, but there will be unknown errors when using training later
But I guess it is still judged that the model is V2 during training

**Comment by GoldenDog1218** [comment]
> 1.5 model requires your huggingface access token

I entered token, but it was removed during screenshot,
After selecting v1.5 model, I will encounter a variable "V2_model" that has not been declared. I can skip this judgment by using parameters such as 1>2, but there will be unknown errors when using training later
But I guess it is still judged that the model is V2 during training

**Comment by tuwonga** [comment]
fixed
